apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: apiserver
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    nodePort: ${apiserver_nodeport}
    protocol: TCP
    targetPort: ${apiserver_port}
  sessionAffinity: ClientIP
  type: NodePort
