
coreos:
  units:
    - name: proxy.service
      command: start
      content: |
        [Unit]
        Description=proxy
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill proxy
        ExecStartPre=-/usr/bin/docker rm proxy
        ExecStartPre=/usr/bin/docker pull vgkowski/squid-transparent-proxy:latest
        ExecStart=/usr/bin/docker run --network=host --name proxy ${upstream_proxy} -e PORT=8080 vgkowski/squid-transparent-proxy:latest

        [Install]
        WantedBy=multi-user.target