coreos:
  units:
  - name: "init-mount-points.service"
    command: "start"
    content: |
      [Unit]
      Description=Create disks mount points
      ConditionPathExists=!/etc/init-mount-points.done

      [Service]
      Type=oneshot
      User=root
      Group=root
      ExecStart=/usr/bin/sh -c 'mkdir -p /mnt/ssd/ssd1 & mkdir -p /mnt/ssd/ssd2 & mkdir -p /mnt/hdd/hdd1 & mkdir -p /mnt/hdd/hdd2'
      ExecStartPost=/bin/touch /etc/init-mount-points.done

      [Install]
      WantedBy=multi-user.target
  - name: "format-disks.service"
    command: "start"
    content: |
      [Unit]
      Description=Format disks
      ConditionPathExists=!/etc/format-disks.done

      [Service]
      Type=oneshot
      User=root
      Group=root
      ExecStart=/usr/bin/sh -c 'sleep 60 ; mkfs.xfs -f /dev/vdb ; mkfs.xfs -f /dev/vdc ; mkfs.xfs -f /dev/vdd ; mkfs.xfs -f /dev/vde'
      ExecStartPost=/bin/touch /etc/format-disks.done

      [Install]
      WantedBy=multi-user.target
  - name: "mnt-ssd-ssd1.mount"
    command: "start"
    content: |
      [Unit]
      Description = SSD1 local Storage

      [Mount]
      What=/dev/vdb
      Where=/mnt/ssd/ssd1
      Type=xfs
      Options=noatime

      [Install]
      WantedBy = multi-user.target
  - name: "mnt-ssd-ssd2.mount"
    command: "start"
    content: |
      [Unit]
      Description = SSD2 local Storage

      [Mount]
      What=/dev/vdc
      Where=/mnt/ssd/ssd2
      Type=xfs
      Options=noatime

      [Install]
      WantedBy = multi-user.target
  - name: "mnt-hdd-hdd1.mount"
    command: "start"
    content: |
      [Unit]
      Description = HDD1 local Storage

      [Mount]
      What=/dev/vdd
      Where=/mnt/hdd/hdd1
      Type=xfs
      Options=noatime

      [Install]
      WantedBy = multi-user.target
  - name: "mnt-hdd-hdd2.mount"
    command: "start"
    content: |
      [Unit]
      Description = HDD2 local Storage

      [Mount]
      What=/dev/vde
      Where=/mnt/hdd/hdd2
      Type=xfs
      Options=noatime

      [Install]
      WantedBy = multi-user.target